import 'package:get/get.dart';

class MyTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          //Ar
          //sing in screen with otp screen --->start

          "1": "تسجيل الدخول بواسطة",
          "2": "رقم الهاتف",
          "3": "البريد الإلكتروني",
          "4": "عند الضغط تسجيل الدخول فأنك توافق على",
          "5": " الشروط & الاحكام",
          "6": "تسجيل الدخول",
          "7": "إدخل رقم الهاتف",
          "8": "إدخل الريد الالكتروني",
          "9": "مرحبا بك في تطبيق دليلي",
          "10": "إدخل رقم التحقق",
          "11": "أدخل الرقم السري لمره واحدة/nالمرسل الى رقم الهاتف",
          "12": "تأكيد",
          "13": "لم يتم الاستلام؟ إعادة إرسال الرقم السري لمرة واحدة",

          //sing in screen with otp screen ---> end
//--------------------
//DASHBOARD screen with shipmment --->start

          "14": "الإحصائيات",
          "15": "تصدير Pdf",
          "16": "تصدير Excell",
          "17": "الإحصائيات الاساسية",
          "18": "الإحصائيات المالية",
          "19": "لا توجد نتائج",
          "20": "الشحنات",
          "21": "كل الشحنات",
          "22": "الشحنات الموصلة",
          "23": "الشحنات\nالموصلة",
          "24": "غير موصلة\nالشحنات",
          "25": "الشحنات غير موصلة",
          "26": "جاهز للتوصيل",
          "27": "الشحنات المسترجعة",
          "28": "المسترجعة\nالشحنات",
          "29": "الشحنات الملغية",
          "30": "الاسم",
          "31": "رقم المرجع",
          "32": "مبالغ مستلمة",
          "33": "إخفاء التفاصيل",
          "34": "عرض التفاصيل",
          "35": "تفاصيل الشحنات",
          "36": "ملخص الدفع",
          "37": "تكلفة الشحنة",
          "38": "الدفع عند الاسنلام",
          "39": "الكلفة الاجمالية",
          "40": "كل الطلبات",
          "41": "إجمالي مبلغ الطلبات",
          "42": "الطلبات المدفوعة",
          "43": "المبلغ المدفوع",
          "44": "المبالغ المقيدة",
          "45": "جاهز للدفع",
          "46": "المبالغ مسلمة للمندوب",
          "47": "المبالغ المسترجعة",
          "48": "الشحنات",
          "49": "مستلمة",
          "50": "مرسلة",
          "51": "تم تحديث البيانات",
          "52": "ادخل رقم الشحنة",

//DASHBOARD screen with shipmment  ---> end
//---------------------------
//Pick Up screen --->Start

          "53": "حدد بواسطة الموقع",
          "54": "حدد بواسطة QRcode",
          "55": "الاستلام",
          "56": "اليوم",
          "57": "كل",
          "58": "تاريخ",
          "59": "السائق",
          "60": "مبلغ مدفوع من تاجر",
          "61": "عدد",
          "62": "الحالة",
          "63": "تفاصيل الاستلام",
          "64": "الوزن",
          "65": "الشحن",
          "66": "رقم الهاتف",
          "67": "الموقع",
          "68": "حدد",
          "69": "حدد الموقع",
          "70": "المحافظة",
          "71": "حدد المحافظة",
          "72": "الولاية",
          "73": "اختر",
          "74": "المنطقة",
          "75": "طلب الاستلام",
          "76": "حدد المنطقة",
          "77": "حدد الولاية",

//Pick Up screen  ---> end
//---------------------------
// other

          "78": "حساباتي",
          "79": "المكاتب",
          "80": "الإعدادات",
          "81": "البلاغات",
          "82": "حساب السعر",
          "83": "تسجيل الخروج",
          "84": "هل متاكد من تسجيل الخروج ؟",
          "85": "نعم",
          "86": "لا",
          "87": "حذف الحساب",
          "88": "هل متاكد من حدف الحساب ؟",
          "89": "مفتوحة",
          "90": "مغلقة",
          "91": "تخزين الكمية المتبقية",
          "92": "إجمالي الطلبات المسلمة",
          "93": "المبلغ الإجمالي للطلب",
          "94": "رسوم التوصيل",
          "95": "رسوم التحصيل",
          "96": "عرض الطلبات",
          "97": "الاستعلامات",
          "98": "إدارة الحسابات",
          "99": "الموعد النهائي",
          "100": "مبلغ الفواتير",
          "101": "فاتورة",
          "102": "PDF ملف",
          "103": "هل متاكد من تحميل الملف ؟",
          "104": "الفروع",
          "105": "قائمة العرض",
          "106": "الخارطة",
          "107": "البحث",
          "108": "فتح بواسطة جوجل ماب",
          "109": "الذهاب الى الموقع",
          "110": "الواتساب",
          "111": "هل تريد الذهاب الى الواتساب ؟",
          "112": "اتصل",
          "113": "هل تريد الاتصال بالرقم؟",
          "114": "ساعات العمل",
          "115": "الاحد",
          "116": "الاثنين",
          "117": "الثلاثاء",
          "118": "الاربعاء",
          "119": "الخميس",
          "120": "الجمعة",
          "121": "السبت",
          "122": "عرض المزيد",
          "123": "فرع",
           "124": "الملف الشخصي",
          "125": "حول التطبيق",
          "126": "الشروط والأحكام",
          "127": "التقيم",
          "128": "اللغة",
          "129": "تحديد اللغة",
          "130": "الرجاء إدخال رقم حسابك",
          "131": "حفظ",
          "132": "رقم البلاغ",
          "133": "رقم الطلب",
          "134": "نوع البلاغ",
          "135": "الموضوع",
         
         
          "136": "تفاصيل البلاغات",
          "137": "الرد",
          "138": "الوصف",
          "139": "المرفق",
          "140": "تاريخ",
          "141": "مرفقات الرسائل",
          "142": "تنزيل",
          "143": "كتابة",
          "144": "إرفاق الملف",
          "145": "من",
          "146": "الى",
          "147": "متابعة",
          "148": "التالي",
          "149": "الرجوع",
          "150": "نوع الشحن",
          "151": "محلي",
          "152": "دولي",
          "153": "وزن جديد",
          "154": "أدخل وزن الشحنة",
          "155": "الشحن من",
          "156": "الشحن الى",
          "157": "يعتمد السعر على السعر النقدي بعملة عمان",
          "158": "أيام",
          "159": "مع دليلي لا حدود للتسليم",
          "160": "تغيير",
          
        
        },
        "en": {
          //En
//sing in screen with otp screen --->Start

          "1": "Login by",
          "2": "Mobile No",
          "3": "Email",
          "4": "by clicking login I am agree with",
          "5": " terms & conditions",
          "6": "Sign in",
          "7": "Enter your mobile number",
          "8": "Enter your email",
          "9": "WELCOME TO DALILEE SHIPPER",
          "10": "Enter the verification code",
          "11":
              "We have sent a 4 digit verification code.\nPlease enter the verification code below",
          "12": "Confirm the code",
          "13": "Resend the verification code again",

//sing in screen with otp screen --->end
//ا
//--------------------
//DASHBOARD screen  with shipmment ---> start

          "14": "DASHBOARD",
          "15": "Export Pdf",
          "16": "Export Excell",
          "17": "Main Dashboard",
          "18": "Finances Dashboard",
          "19": "No data",
          "20": "Shipments",
          "21": "All Shipments",
          "22": "Delivered Shipments",
          "23": "Delivered\nShipments",
          "24": "Un-Delivered\nShipments",
          "25": "Un-Delivered Shipments",
          "26": "Out For Delivery OFD",
          "27": "Return Shipments",
          "28": "Returned\nShipments",
          "29": "Cancel Shipments",
          "30": "Name",
          "31": "Ref",
          "32": "CC",
          "33": "Hide Details",
          "34": "Show More Details",
          "35": "Shipment Journey",
          "36": "Payment Summary",
          "37": "Shipping Cost",
          "38": "COD",
          "39": "Total Charges",
          "40": "All Orders",
          "41": "Total Orders Amount",
          "42": "Paid Orders",
          "43": "Paid Amount",
          "44": "COD Pending",
          "45": "Ready To Pay",
          "46": "COD with Drivers",
          "47": "COD Return",
          "48": "SHIPMENTS",
          "49": "IN",
          "50": "OUT",
          "51": "Updated data",
          "52": "Enter Shipment Number",

//DASHBOARD screen with shipmment  ---> end
//---------------------------
//Pick Up screen --->Start

          "53": "Pick by Location",
          "54": "Pick by QRcode",
          "55": "PICKUP",
          "56": "Today",
          "57": "All",
          "58": "Date",
          "59": "Driver",
          "60": "COP",
          "61": "Quantity",
          "62": "status",
          "63": "Details Pickup",
          "64": "Weight",
          "65": "Shipping",
          "66": "Phone",
          "67": "Location",
          "68": "Pick",
          "69": "Pick Address",
          "70": "Muhafaza",
          "71": "Select Muhafaza",
          "72": "Wilaya",
          "73": "select",
          "74": "Region",
          "75": "Request Pickup",
          "76": "select region",
          "77": "wilaya region",

//Pick Up  screen with shipmment  ---> end
//---------------------------
// other
          "78": "Finance",
          "79": "Offices",
          "80": "Settings",
          "81": "Ticket",
          "82": "Calculate",
          "83": "Log out",
          "84": "Are you sure you want to log out ?",
          "85": "Ok",
          "86": "Cancel",
          "87": "Delete Account",
          "88": "Are you sure you want to delete your account ?",
          "89": "Opened",
          "90": "Closed",
          "91": "Store Remaining Amount",
          "92": "Total Orders Delivered",
          "93": "Total Amount of Request",
          "94": "Delivery Fee",
          "95": "Collection Fee",
          "96": "View Orders",
          "97": "Finance Inquiry",
          "98": "Manage Accounts",
          "99": "Closing Date",
          "100": "Invoices Amount",
          "101": "Invoice",
          "102": "PDF File",
          "103": "Are you sure to download pdf file?",
          "104": "BRANCHES",
          "105": "List View",
          "106": "Map View",
          "107": "Search",
          "108": "Open View In Gooole Map",
          "109": "Go To Location",
          "110": "Whatsapp",
          "111": "Are you want to go to whatsapp?",
          "112": "Call",
          "113": "Are you want to call?",
          "114": "Working Hours",
          "115": "Sunday",
          "116": "Monday",
          "117": "Tuesday",
          "118": "WenDay",
          "119": "Thursday",
          "120": "Friday",
          "121": "Saturday",
          "122": "Show More",
          "123": "Branch",

          "124": "Profile",
          "125": "About The App",
          "126": "Terms & Conditions",
          "127": "Rating",
          "128": "Language",
          "129": "Select Language",
          "130": "please enter your account number",
          "131": "Save",
          "132": "Ticket No",
          "133": "Order No",
          "134": "Ticket Type",
          "135": "Subject",

          "136": "Ticket Details",
          "137": "Reply",
          "138": "Description",
          "139": "Attachment",
          "140": "Created at",
          "141": "Message Attachments",
          "142": "Download",
          "143": "writing",
          "144": "Attach File",
          "145": "FROM",
          "146": "TO",
          "147": "Proceed",
          "148": "Next",
          "149": "Back",
          "150": "Shipping Type",
          "151": "Domestic",
          "152": "International",
          "153": "New Weight",
          "154": "Enter Shipment Weight",
          "155": "Shipping From",
          "156": "Shipping To",
          "157": "Rate is based on cash rate in Oman Currency",
          "158": "Days",
          "159": "With Dalilee, there is no boundary for delivery",
          "160": "Change",

          // "160": "Mobile Number",
          // "160": "Joining Date",
          // "160": "Logo",
          // "160": "Choose Logo",
          // "160": "Manage Address",
          // "160": "Main Address",
          // "160": "Main Address",
          // "160": "Main Address",
          
        
        },
      };
}
