import 'package:get/get.dart';

class MyTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "userName": "أسم المستخدم",
          "password": "كلمة المرور",
          "enteryourusername": "الرجاء إدخال أسم المستخدم",
          "SearchOrder": "ترتيب البحث",
          "pickAddress": "اختر العنوان",
          "instagramLink": "انستغرام",
          "Recievable": "مستحق",
          "Payable": "مستحق الدفع",
          "accountType": "نوع الحساب",
          "Location": "موقع",
          "TotalCC": "إجمالي النقد المحصل",
          "ExpressPickup": "الاستلام السرريع",
          "resend_otp": "إعادة إرسال OTP",
          "verify": "يؤكد",
          "enter_otp_to_verify": "أدخل OTP لإنشاء استعلام",
          "call_attempts": "محاولة الاتصال",
          "call_driver": "الإتصال بالمندوب",
          "call_customer": "الإتصال بالعميل",
          "whatsapp_customer": "واتساب العميل",
          "whatsapp_driver": "واتساب المندوب",

          "delivery_attempts": "محاولة التوصيل",
          "app_expired": "هذا الاصدار من التطبيق ملغي",
          "please_update": "الرجاء تحديث التطبيق",
          "upgrade_now": "تحديث الان",

          "version": "اصدار التطبيق : ",
          "Orders": "الشحنة",
          "Delivered": "تم التوصيل",
          "Un-Delivered": "لم يتم تسليمها",
          "da1": "محاولة تسليم الطلب ١",
          "da2": "محاولة تسليم الطلب ٢",
          "ca1": "محاولة الاتصال ١",
          "ca2": "محاولة الاتصال ٢",
          "all": "الكل",
          "To": "الى",
          "From": "من",
          "write_order_number": "الرجاء كتابة رقم تتبع الشحنة",
          "search_order": "البحث عن الشحنة",

          "totalOrderDeliver": "إجمالي الطلبات التي تم تسليمها",
          "closingDate": "الموعد النهائي",
          "invoiceAmoint": "مبلغ الفواتير",
          "Notifications": "إشعارات",
          "sendOtp": "أرسل OTP",
          "otpSent": "تم إرسال OTP بنجاح",
          "enableEditing": "تفعيل التحرير",
          "storeName": "اسم المتجر",
          "mobile": "رقم الهاتف المحمول",
          "Email": "بريد إلكتروني",

          "joinDate": "تاريخ الانضمام",
          "Logo": "شعار",
          "chooseLogo": "اختر الشعار",
          "myOrders": "طلباتي",
          "chooseCurrency": "اختر العملة",
          "enterName": "من فضلك أدخل إسمك",
          "expectedAmount": "المبلغ المتوقع",
          "requestDate": "تاريخ الطلب",
          "notes": "ملاحظات",
          "pickupImage": "صورة الالتقاط",
          "deliveredImage": "تسليم الصورة",
          "undeliverImage": "لم يتم تسليم الصورة",
          "aed": "درهم",
          "omr": "عمان ريال",
          "Address": "عنوان:",
          "WhatsappNo": "رقم هاتف الواتساب",
          "soon_available": "هذه الميزه ستتوفر قريبا",
          "bank_added": "تم اضافة الحساب البنكي بنجاح",
          "done": "Done",
          "selectaccount": "اختر الحساب البنكي",
          "bankaccount": "حساب البنك",
          "expected_amount": "المبلغ التقديري",
          "write_here": "اكتب هنا",
          'required': "مطلوب",
          "EnquiryNo": "رقم الطلب",
          "enq_addedd": "تم اضافة طلبك بنجاح",
          "OrderId#": "رقم الشحنة : ",

          "check_data": "الرجاء التاكد من الاتصال بالانترنت",
          "less_amount_warning":
              "المبلغ المستحق اقبل من 1 ريال عماني , لايمكنك تقديم الطلب",
          "PickupTime": "وقت الاستلام",
          "AutoCreatePickup": "طلب استلام تلقائي",
          "Note": "ملاحظة",
          "DailyPickupNote": "سيتم انشاء طلب استلام يوميا بشكل تلقائي",
          "Proceed": "موافق",
          "PickAddress": "عنوان طلب الاستلام",
          "DailyPickup": "طلب استلام يومي",
          "Solve": "حل",
          "ProblemImage": "صورة المشكلة",

          "Add": "إضافة",
          "AddOrder": "إضافة طلب جديد",

          // //////new words for mishwar
          "AddItem": "إضافة منتج",
          "Update": "تحديث",
          "Something went wront. Please try again later":
              "حدث خطأ , الرجاء المحاولة لاحقا",
          "Problem comments has been updated successfully":
              "تم تحديث المشكلة بنجاح",
          "Failed": "فشل",
          "Success": "نجاح",
          //Ar
          //sing in screen with otp screen --->start

          "Loginby": "تسجيل الدخول ",
          "MobileNo": "رقم الهاتف",
          "clickingAgree": "عند الضغط تسجيل الدخول فأنك توافق على",
          "terms&conditions": " الشروط & الاحكام",
          "Signin": "تسجيل الدخول",
          "Entermobile": "إدخل رقم الهاتف",
          "Enteryouremail": "إدخل الريد الالكتروني",
          "WELCOMETODALILEE": "مرحبا بك في تطبيق دليلي",
          "Entertheverification": "إدخل رقم التحقق",
          "Wehavesent": "أدخل الرقم السري لمره واحدةالمرسل الى رقم الهاتف",
          "Confirmthecode": "تأكيد",
          "Resendverification":
              "لم يتم الاستلام؟ إعادة إرسال الرقم السري لمرة واحدة",

          //sing in screen with otp screen ---> end
//--------------------
//DASHBOARD screen with shipmment --->start

          "DASHBOARD": "الإحصائيات",
          "ExportPdf": "تصدير Pdf",
          "ExportExcell": "تصدير Excell",
          "MainDashboard": "احصائيات الاساسية",
          "FinancesDashboard": "احصائيات المالية",
          "NoData": "لا توجد نتائج",
          "Shipments": "الشحنات",
          "AllShipments": "كل الشحنات",
          "DeliveredShipments": "الشحنات الموصلة",
          "DeliverednShipments": "الشحنات\nالموصلة",
          "Un-DeliverednShipments": "الشحنات\nغير الموصلة",
          "Un-DeliveredShipments": "الشحنات غير موصلة",
          "OFD": "جاهز للتوصيل",
          "ReturnShipments": "الشحنات المسترجعة",
          "ReturnednShipments": "الشحنات\nالمسترجعة",
          "CancelShipments": "الشحنات الملغية",
          "Name": "الاسم",
          "thisaccounttransferred":
              " هذا الحساب الذي سيتم تحويل جميع الأموال علية",
          "Ref": "رقم المرجع",
          "CC": "مبالغ مستلمة",
          "HideDetails": "إخفاء التفاصيل",
          "ShowMoreDetails": "عرض التفاصيل",
          "ShipmentJourney": "تفاصيل الشحنات",
          "PaymentSummary": "ملخص الدفع",
          "ShippingCost": "تكلفة الشحنة",
          "COD": "الدفع عند الاسنلام",
          "TotalCharges": "الكلفة الاجمالية",
          "AllOrders": "كل الطلبات",
          "TotalOrdersAmount": "مبلغ الاجمالي للطلبات",
          "PaidOrders": "الطلبات المدفوعة",
          "PaidAmount": "مبالغ مدفوعة",
          "CODPending": "مبالغ مقيدة",
          "ReadyToPay": "جاهز للدفع",
          "CODwithDrivers": "مبالغ مسلمة للمندوب",
          "CODReturn": "مبالغ مسترجعة",
          "SHIPMENTS": "الشحنات",
          "IN": "مستلمة",
          "OUT": "مرسلة",
          "Updateddata": " تحديث البيانات",
          "EnterShipmentNumber": "ادخل رقم الشحنة",

//DASHBOARD screen with shipmment  ---> end
//---------------------------
//Pick Up screen --->Start

          "PickbyLocation": "حدد بواسطة الموقع",
          "PickbyQRcode": "حدد بواسطة QRcode",
          "PICKUP": "الاستلام",
          "Today": "اليوم",
          "All": "كل",
          "Date": "تاريخ",
          "Driver": "السائق",
          "COP": "مبلغ مدفوع من تاجر",
          "Quantity": "عدد",
          "status": "الحالة",
          "DetailsPickup": "تفاصيل الاستلام",
          "Weight": "الوزن",
          "Shipping": "الشحن",
          "Phone": "رقم الهاتف",
          "Location": "الموقع",
          "Pick": "حدد",
          "Muhafaza": "المحافظة",
          "SelectMuhafaza": "حدد المحافظة",
          "Wilaya": "الولاية",
          "select": "اختر",
          "Region": "المنطقة",
          "RequestPickup": "طلب الاستلام",
          "selectregion": "حدد المنطقة",
          "wilayaregion": "حدد الولاية",

//Pick Up screen  ---> end
//---------------------------
// other

          "Finance": "حساباتي",
          "Offices": "المكاتب",
          "Settings": "الإعدادات",
          "Ticket": "البلاغات",
          "Calculate": "حساب السعر",
          "Logout": "تسجيل الخروج",

          "Areyoulogout": "هل متاكد من تسجيل الخروج ؟",
          "Ok": "نعم",
          "Cancel": "لا",
          "DeleteAccount": "حذف الحساب",
          "Aredeleteaccount": "هل متاكد من حدف الحساب ؟",
          "Opened": "مفتوحة",
          "Closed": "مغلقة",
          "StoreRemainingAmount": "تخزين الكمية المتبقية",
          "TotalOrdersDelivered": "إجمالي الطلبات المسلمة",
          "TotalAmountRequest": "المبلغ الإجمالي للطلب",
          "DeliveryFee": "رسوم التوصيل",
          "CollectionFee": "رسوم التحصيل",
          "ViewOrders": "عرض الطلبات",
          "FinanceInquiry": "الاستعلامات",
          "RequestInquiry": "طلب استعلام",
          "ManageAccounts": "إدارة الحسابات",
          "ClosingDate": "الموعد النهائي",
          "InvoicesAmount": "مبلغ الفواتير",
          "Invoice": "فاتورة",
          "PDFFile": "PDF ملف",
          "AreDownloadpdf": "هل متاكد من تحميل الملف ؟",
          "BRANCHES": "الفروع",
          "ListView": "قائمة العرض",
          "MapView": "الخارطة",
          "Search": "البحث",
          "OpenGoooleMap": "فتح بواسطة جوجل ماب",
          "GoLocation": "الذهاب الى الموقع",
          "Whatsapp": "الواتساب",
          "AreWhatsapp": "هل تريد الذهاب الى الواتساب ؟",
          "Call": "اتصل",
          "AreCall": "هل تريد الاتصال بالرقم؟",
          "WorkingHours": "ساعات العمل",
          "Sunday": "الاحد",
          "Monday": "الاثنين",
          "Tuesday": "الثلاثاء",
          "WenDay": "الاربعاء",
          "Thursday": "الخميس",
          "Friday": "الجمعة",
          "Saturday": "السبت",
          "ShowMore": "عرض المزيد",
          "Branch": "فرع",
          "Profile": "الملف الشخصي",
          "AboutApp": "حول التطبيق",
          "Terms&Conditions": "الشروط والأحكام",
          "Rating": "التقيم",
          "Language": "اللغة",
          "SelectLanguage": "تحديد اللغة",
          "enterAccount": "الرجاء إدخال رقم حسابك",
          "selectBank": "الرجاء تحديد البنك",
          "maxlimit": "العدد الأقصى 20",

          "AccountNumber": "رقم الحساب",
          "BeneficiaryName": "اسم المستفيد",
          "Save": "حفظ",
          "TicketNo": "رقم البلاغ",
          "OrderNo": "رقم الطلب",
          "TicketType": "نوع البلاغ",
          "Subject": "الموضوع",
          "categoryType": "نوع الفئة",
          "SelectcategoryType": "اختر نوع الفئة",

          "subcategoryType": "نوع الفئة الفرعية",
          "Selectsubcategory": "اختر نوع الفئة الفرعية",

          "ExplainyourInquiry": "اشرح استفسارك",
          "CreateInquiry": "انشاء استعلام",
          "Create": "انشاء",

          "TicketDetails": "تفاصيل البلاغات",
          "Reply": "الرد",
          "Description": "الوصف",
          "Attachment": "المرفق",
          "CreatedAt": "تاريخ",
          "MessageAttachments": "مرفقات الرسائل",
          "Download": "تنزيل",
          "writing": "اكتب...",
          "AttachFile": "إرفاق الملف",
          "FROM": "من",
          "TO": "الى",
          "Next": "التالي",
          "Back": "الرجوع",
          "WEIGHT": "وزن",

          "ShippingType": "نوع الشحن",
          "Domestic": "محلي",
          "International": "دولي",
          "NewWeight": "وزن جديد",
          "EnterWeight": "أدخل وزن الشحنة",
          "ShippingFrom": "الشحن من",
          "ShippingTo": "الشحن الى",
          "RateIsbased": "يعتمد السعر على السعر النقدي بعملة عمان",
          "Days": "أيام",
          "WithDalilee": "مع دليلي لا حدود للتسليم",
          "Change": "تغيير",
          "RequestTicket": "تقديم بلاغ",
          "ExplainyourTicket": "اشرح بلاغك",
          "SelectTicketType": "اختر نوع البلاغ",
          "ENORAR": "ar",
          "AddBankAccount": "اضافة حساب جديد",
          "bankaccountaddedsuccessfully": "تم اضافة الحاسب بنجاح",
          "BankMuscat": "بنك مسقط",
          "Bank": "بنك",
          "InquiryNo": "رقم الاستفسار",
          "GenerateTicket": "تذكرة جديده",
          "DownloadBill": "تحميل الايصال",
          "CopyNumber": "نسخ الرقم",
          "WhatsAppMessage": "الواتساب",
          "SMS": "رسالة نصية",
          "Copyphonenumber": "تم نسخ الرقم",

          "addcomplainsuccessfully": "تم اضافة بلاغ بنجاح",
          "somedatamissing": "بعض البيانات مفقودة",
          "Filed": "فشل",
        },
        "en": {
          "userName": "User Name",
          "password": "Password",
          "enteryourusername": "Enter your username",
          "SearchOrder": "Search Order",

          "Location": "Location",
          "accountType": "Account Type",
          "Payable": "Payable",
          "Recievable": "Recievable",
          "instagramLink": "Instagram Link",
          "pickAddress": "Pick Address",
          "TotalCC": "Total Collected Cash",
          "ExpressPickup": "Express Pickup",
          "resend_otp": "Resend OTP",
          "enter_otp_to_verify": "Enter OTP to Create Enquiry",
          "verify": "Verify",
          "call_driver": "Call Driver",
          "call_customer": "Call Customer",
          "whatsapp_customer": "Whatsapp Customer",
          "whatsapp_driver": "Whatsapp Driver",
          "call_attempts": "Call Attempts",
          "delivery_attempts": "Delivery Attempts",
          "app_expired": "Application Version Expired",
          "please_update": "Please Update",
          "upgrade_now": "Upgrade Now",
          "Delivered": "Delivered",
          "version": "App Version : ",
          "Orders": "Orders",

          "Un-Delivered": "Un-Delivered",
          "da1": "Delivery Attempt 1",
          "da2": "Delivery Attempt 2",
          "ca1": "Call Attempt 1",
          "ca2": "Call Attempt 2",
          "all": "All",
          "To": "To",
          "From": "From",
          "Search": "Search",
          "write_order_number": "write order number",
          "search_order": "Search Order",

          "totalOrderDeliver": "Total Orders Delivered",
          "closingDate": "Closing Date",
          "invoiceAmoint": "Invoices Amount",
          "Notifications": "Notifications",
          "sendOtp": "Send OTP",
          "otpSent": "OTP Sent Successfully",
          "profile": "Profile",
          "enableEditing": "Enable Editing",
          "storeName": "Store Name",
          "Email": "Email",
          "mobile": "Mobile Number",
          "joinDate": "Joining Date",
          "Logo": "Logo",
          "chooseLogo": "Choose Logo",
          "myOrders": "My Orders",
          //En
          "chooseCurrency": "Choose Currency",
          "enterName": "please enter your name",
          "expectedAmount": "Expected Amount",
          "requestDate": "Request Date",
          "notes": "Notes",

          "pickupImage": "Pickup Image",
          "deliveredImage": "Delivered Image",
          "undeliverImage": "Undelivered Image",

          "aed": "AED",
          "omr": "OMR",
          "Address": "Address:",
          "WhatsappNo": "Whatsapp Number",
          "soon_available": "This feature will available soon",
          "bank_added": "Bank account added successfully",
          "done": "Done",
          "selectaccount": "Select bank account",
          "bankaccount": "Bank Account",
          "expected_amount": "Expected Amount",
          "write_here": "write here",
          'required': "required",
          "EnquiryNo": "Enquiry No",
          "enq_addedd": "Enquiry successfully added",
          "Failed": "Failed",
          "check_data": "Please check your data",
          "OrderId#": "Order No : ",

          "less_amount_warning":
              "Your pending amount is less than 1 OMR, you can not create enquiry",
          "PickupTime": "PickupTime:",
          "AutoCreatePickup": "Auto Create Pickup",
          "Note": "Note",
          "DailyPickupNote":
              "Your pickup reference will be created automatically on daily basis",
          "Proceed": "Proceed",
          "PickAddress": "Pick Address",
          "DailyPickup": "Daily Auto Pickup",
          "Solve": "Solve",
          "ProblemImage": "Problem Image",
          "AddOrder": "Add Order",
          "Add": "Add",

          // //////new words for mishwar
          "AddItem": "Add Item",
          "Update": "Update",
          "Something went wront. Please try again later":
              "Something went wront. Please try again later",
          "Problem comments has been updated successfully":
              "Problem comments has been updated successfully",
          "Success": "Success",

//sing in screen with otp screen --->Start
          "Filed": "Failed",
          "somedatamissing": "some data was missing",
          "addcomplainsuccessfully": "Complain added successfully",
          "Loginby": "Login by",
          "MobileNo": "Mobile No",
          "clickingAgree": "by clicking login I am agree with ",
          "terms&conditions": "terms & conditions",
          "Signin": "Sign in",
          "Entermobile": "Enter your mobile number",
          "Enteryouremail": "Enter your email",
          "WELCOMETODALILEE": "WELCOME TO DALILEE SHIPPER",
          "Entertheverification": "Enter the verification code",
          "Wehavesent":
              "We have sent a 4 digit verification code.\nPlease enter the verification code below",
          "Confirmthecode": "Confirm the code",
          "Resendverification": "Resend the verification code again",

//sing in screen with otp screen --->end
//ا
//--------------------
//DASHBOARD screen  with shipmment ---> start

          "DASHBOARD": "DASHBOARD",
          "ExportPdf": "Export Pdf",
          "ExportExcell": "Export Excell",
          "MainDashboard": "Main Dashboard",
          "FinancesDashboard": "Finances Dashboard",
          "NoData": "No data",
          "Shipments": "Shipments",
          "AllShipments": "All Shipments",
          "DeliveredShipments": "Delivered Shipments",
          "DeliverednShipments": "Delivered\nShipments",
          "Un-DeliverednShipments": "Un-Delivered\nShipments",
          "Un-DeliveredShipments": "Un-Delivered Shipments",
          "OFD": "Out For Delivery OFD",
          "ReturnShipments": "Return Shipments",
          "ReturnednShipments": "Returned\nShipments",
          "CancelShipments": "Cancel Shipments",
          "Name": "Name",
          "Ref": "Ref",
          "thisaccounttransferred":
              "this account which all money will be transferred",

          "CC": "CC",
          "HideDetails": "Hide Details",
          "ShowMoreDetails": "Show More Details",
          "ShipmentJourney": "Shipment Journey",
          "PaymentSummary": "Payment Summary",
          "ShippingCost": "Shipping Cost",
          "COD": "COD",
          "TotalCharges": "Total Charges",
          "AllOrders": "All Orders",
          "TotalOrdersAmount": "Total Orders Amount",
          "PaidOrders": "Paid Orders",
          "PaidAmount": "Paid Amount",
          "CODPending": "Pending Shipments COD ",
          "ReadyToPay": "Ready To Pay",
          "CODwithDrivers": "COD OFD",
          "CODReturn": "COD Returned",
          "SHIPMENTS": "SHIPMENTS",
          "IN": "IN",
          "OUT": "OUT",
          "Updateddata": "Update data",
          "EnterShipmentNumber": "Enter Shipment Number",

//DASHBOARD screen with shipmment  ---> end
//---------------------------
//Pick Up screen --->Start

          "PickbyLocation": "Pick by Location",
          "PickbyQRcode": "Pick by QRcode",
          "PICKUP": "PICKUP",
          "Today": "Today",
          "All": "All",
          "Date": "Date",
          "Driver": "Driver",
          "COP": "COP",
          "Quantity": "Quantity",
          "status": "status",
          "DetailsPickup": "Details Pickup",
          "Weight": "Weight",
          "Shipping": "Shipping",
          "Phone": "Phone",
          "Location": "Location",
          "Pick": "Pick",
          "Muhafaza": "Muhafaza",
          "SelectMuhafaza": "Select Muhafaza",
          "Wilaya": "Wilaya",
          "select": "select",
          "Region": "Region",
          "RequestPickup": "Request Pickup",
          "selectregion": "select region",
          "wilayaregion": "wilaya region",

//Pick Up  screen with shipmment  ---> end
//---------------------------
// other
          "Finance": "Finance",
          "Offices": "Offices",
          "Settings": "Settings",
          "Ticket": "Ticket",
          "Calculate": "Calculate",
          "Logout": "Log out",
          "Areyoulogout": "Are you sure you want to log out ?",
          "Ok": "Ok",
          "Cancel": "Cancel",
          "DeleteAccount": "Delete Account",
          "Aredeleteaccount": "Are you sure you want to delete your account ?",
          "Opened": "Opened",
          "Closed": "Closed",
          "StoreRemainingAmount": "Store Remaining Amount",
          "TotalOrdersDelivered": "Total Orders Delivered",
          "TotalAmountRequest": "Total COD",
          "DeliveryFee": "Delivery Fee",
          "CollectionFee": "Collection Fee",
          "ViewOrders": "View Orders",
          "FinanceInquiry": "Finance Enquiry",
          "RequestInquiry": "Request Enquiry",
          "ManageAccounts": "Manage Accounts",
          "ClosingDate": "Closing Date",
          "InvoicesAmount": "Invoices Amount",
          "Invoice": "Invoice",
          "PDFFile": "PDF File",
          "AreDownloadpdf": "Are you sure to download pdf file?",
          "BRANCHES": "BRANCHES",
          "ListView": "List View",
          "MapView": "Map View",
          "OpenGoooleMap": "Open View In Gooole Map",
          "GoLocation": "Go To Location",
          "Whatsapp": "Whatsapp",
          "AreWhatsapp": "Are you want to go to whatsapp?",
          "Call": "Call",
          "AreCall": "Are you want to call?",
          "WorkingHours": "Working Hours",
          "Sunday": "Sunday",
          "Monday": "Monday",
          "Tuesday": "Tuesday",
          "WenDay": "WenDay",
          "Thursday": "Thursday",
          "Friday": "Friday",
          "Saturday": "Saturday",
          "ShowMore": "Show More",
          "Branch": "Branch",

          "Profile": "Profile",
          "AboutApp": "About The App",
          "Terms&Conditions": "Terms & Conditions",
          "Rating": "Rating",
          "Language": "Language",
          "SelectLanguage": "Select Language",
          "enterAccount": "please enter your account number",
          "selectBank": "please select bank",
          "maxlimit": "max number 20",

          "AccountNumber": "Account Number",
          "BeneficiaryName": "Beneficiary Name",

          "Save": "Save",
          "TicketNo": "Ticket No",
          "OrderNo": "Order No",
          "TicketType": "Ticket Type",
          "Subject": "Subject",
          "categoryType": "category Type",
          "SelectcategoryType": "Select category Type",
          "subcategoryType": "sub category Type",
          "Selectsubcategory": "Select sub category",
          "ExplainyourInquiry": "Explain your Inquiry",
          "CreateInquiry": "Create Inquiry",
          "Create": "Create",

          "TicketDetails": "Ticket Details",
          "Reply": "Reply",
          "Description": "Description",
          "Attachment": "Attachment",
          "CreatedAt": "Created at",
          "MessageAttachments": "Message Attachments",
          "Download": "Download",
          "writing": "writing",
          "AttachFile": "Attach File",
          "FROM": "FROM",
          "TO": "TO",
          "Next": "Next",
          "Back": "Back",
          "WEIGHT": "WEIGHT",
          "ShippingType": "Shipping Type",
          "Domestic": "Domestic",
          "International": "International",
          "NewWeight": "New Weight",
          "EnterWeight": "Enter Shipment Weight",
          "ShippingFrom": "Shipping From",
          "ShippingTo": "Shipping To",
          "RateIsbased": "Rate is based on cash rate in Oman Currency",
          "Days": "Days",
          "WithDalilee": "With Dalilee, there is no boundary for delivery",
          "Change": "Change",
          "RequestTicket": "Request Ticket",
          "SelectTicketType": "Select Ticket Type",
          "ExplainyourTicket": "Explain your Ticket",

          "ENORAR": "en",
          "AddBankAccount": "Add Bank Account",
          "bankaccountaddedsuccessfully": "Bank account successfully added",
          "BankMuscat": "select bank",
          "Bank": "Bank",
          "InquiryNo": "Inquiry No",
          "GenerateTicket": "Generate Ticket",
          "DownloadBill": "Download Bill",
          "CopyNumber": "Copy Number",
          "WhatsAppMessage": "WhatsApp",
          "SMS": "SMS",
          "Copyphonenumber": 'Copy phone number',
        },
      };
}
